# Generated by Django 4.0.4 on 2022-07-27 15:15

import VerificacionesApp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField()),
                ('linkDireccion', models.CharField(max_length=200)),
                ('localidadAfectada', models.CharField(max_length=200)),
                ('tipoEvento', models.CharField(max_length=200)),
                ('fechaDelEvento', models.DateField()),
                ('nombreFuente', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('areaPimetAfectada', models.CharField(max_length=200)),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=VerificacionesApp.models.get_image_filename, verbose_name='Image')),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='VerificacionesApp.evento')),
            ],
            options={
                'verbose_name': 'Imagen',
                'verbose_name_plural': 'Imagenes',
            },
        ),
    ]
